#!/usr/bin/env Rscript
##  MRH 29032014 
##
##
##  whitelistgen.R v0, This script is used to generate a whitelist.csv used in:
##
##  Lafon-Placette, C. et al. (2018) ‘Paternally expressed imprinted genes associate with hybridization barriers in Capsella’, Nature Plants. Nature Publishing Group, 4(6), pp. 352–357. doi: 10.1038/s41477-018-0161-6. https://doi.org/10.1038/s41477-018-0161-6
##
##  This source code file is part of the analysis pipeline Imprintia
##  Copyright (C) 2016 Marcelinus Rocky Hatorangan
## 
##  This program is free software: you can redistribute it and/or modify
##  it under the terms of the GNU General Public License as published by
##  the Free Software Foundation, either version 3 of the License, or
##  (at your option) any later version.
## 
##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License for more details.
## 
##  You should have received a copy of the GNU General Public License
##  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##
##  Please cite this pipeline if you use it in your work
##
##  Marcelinus Rocky Hatorangan <marcelinusrocky@aol.com>
##  31 March 2016
##
##  Tested on Ubuntu 14.04

rm(list = ls())

args <- commandArgs(TRUE)

#Opt section
library('optparse')
option_list = list(
	make_option(c("-i", "--input"), type = "character", default = NULL, help = "parent input", metavar = "character"),
	make_option(c("-o", "--output"), type = "character", default = NULL, help = "parent input", metavar = "character")
)

opt_parser = OptionParser(option_list= option_list)
opt = parse_args(opt_parser)
#End of opt section


reads <- read.table(opt$input, header= TRUE, sep= "\t", row.names= 1) 
newreads <- reads 
samplemean <- rowMeans(reads[,c("AxBr1", "AxBr2", "BxAr1", "BxAr2")]) 
newreads <- cbind(newreads,samplemean) 
readscolsum <- colSums(newreads) 

#Generate simple quantity normalization
newreads$Control <- reads$Control/readscolsum[1] 
newreads$AxBr1 <- newreads$AxBr1/readscolsum[2] 
newreads$AxBr2 <- newreads$AxBr2/readscolsum[3] 
newreads$BxAr1 <- newreads$BxAr1/readscolsum[4] 
newreads$BxAr2 <- newreads$BxAr2/readscolsum[5] 
newreads$samplemean <- newreads$samplemean/readscolsum[6] 

#Generate tolerance column with a tight arbitrary number of 0.8 or ~60% maternal contamination.
#This arbitrary number is generated by using trial and error for minimum false discovery rate and maximum identification of imprinted genes needed for the analysis.

newreads$tolerance <- newreads$Control * 0.8 

#The process below will discard any loci with expression level below 0.8 of the control tolerance level in all RNA library.
newreads <- subset(newreads, tolerance <= AxBr1 | tolerance <= AxBr2 | tolerance <= BxAr1 | tolerance <= BxAr2) 

write.table(newreads, file= paste(opt$output,"calc.csv", sep= ""), sep= "\t", quote= FALSE, row.names= TRUE, col.names= TRUE) 
write.table(newreads[,1] file= paste(opt$output,".csv", sep= ""), sep= "\t", quote= FALSE, row.names= TRUE, col.names= TRUE) 
